-- Kitty Script v3.2 (Final: более плотная тонировка, transparency=0.3, no GUI recolor, стек уведомлений 2 шт.)
local P=game:GetService("Players");local UIS=game:GetService("UserInputService");local RS=game:GetService("RunService");local TS=game:GetService("TweenService");local L=game:GetService("Lighting")
local pl=P.LocalPlayer;local pg=pl:WaitForChild("PlayerGui");local m=pl:GetMouse();local cam=workspace.CurrentCamera
UIS.MouseBehavior=Enum.MouseBehavior.Default;UIS.MouseIconEnabled=true

local notifGui=Instance.new("ScreenGui",pg);notifGui.Name="KittyNotif";notifGui.ResetOnSpawn=false;notifGui.DisplayOrder=9999

-- ════════════════════════════════
--   НОВАЯ СИСТЕМА УВЕДОМЛЕНИЙ (стек из 2 сообщений, уезжают вправо)
-- ════════════════════════════════
local notifQueue = {}
local notifSpacing = 60
local notifStartY = -70

local function showNotif(text, color)
    color = color or Color3.fromRGB(90,80,200)
    
    local frame = Instance.new("Frame", notifGui)
    frame.Size = UDim2.new(0,260,0,50)
    frame.Position = UDim2.new(1,20,1,notifStartY)
    frame.BackgroundColor3 = Color3.fromRGB(10,8,20)
    frame.BorderSizePixel = 0
    frame.ZIndex = 10
    Instance.new("UICorner", frame).CornerRadius = UDim.new(0,10)
    
    local st = Instance.new("UIStroke", frame)
    st.Color = color
    st.Thickness = 1.2
    st.Transparency = 0.2
    
    local bar = Instance.new("Frame", frame)
    bar.Size = UDim2.new(0,3,1,-12)
    bar.Position = UDim2.new(0,0,0,6)
    bar.BackgroundColor3 = color
    bar.BorderSizePixel = 0
    Instance.new("UICorner", bar).CornerRadius = UDim.new(0,4)
    
    local lbl = Instance.new("TextLabel", frame)
    lbl.Size = UDim2.new(1,-18,1,0)
    lbl.Position = UDim2.new(0,14,0,0)
    lbl.BackgroundTransparency = 1
    lbl.Text = text
    lbl.TextColor3 = Color3.fromRGB(215,212,255)
    lbl.TextSize = 13
    lbl.Font = Enum.Font.GothamSemibold
    lbl.TextWrapped = true
    lbl.TextXAlignment = Enum.TextXAlignment.Left
    lbl.ZIndex = 11
    
    -- Анимация появления
    TS:Create(frame, TweenInfo.new(0.3, Enum.EasingStyle.Quint, Enum.EasingDirection.Out), {
        Position = UDim2.new(1,-275,1,notifStartY)
    }):Play()
    
    local notifData = { frame = frame, yOffset = notifStartY }
    table.insert(notifQueue, 1, notifData)
    
    -- Обновляем позиции всех уведомлений
    local function updatePositions()
        for i, data in ipairs(notifQueue) do
            local newY = notifStartY - (i - 1) * notifSpacing
            if data.frame and data.frame.Parent then
                data.frame.Position = UDim2.new(1,-275,1,newY)
                data.yOffset = newY
            end
        end
    end
    updatePositions()
    
    -- Если больше 2 уведомлений, удаляем самое старое (уезжает вправо)
    if #notifQueue > 2 then
        local oldest = table.remove(notifQueue)
        if oldest and oldest.frame and oldest.frame.Parent then
            local tweenOut = TS:Create(oldest.frame, TweenInfo.new(0.4, Enum.EasingStyle.Quint, Enum.EasingDirection.In), {
                Position = UDim2.new(1,20,1,oldest.yOffset)
            })
            tweenOut:Play()
            tweenOut.Completed:Connect(function()
                if oldest.frame then oldest.frame:Destroy() end
            end)
        end
    end
    
    -- Автоудаление через 4 секунды (уезжает вправо)
    task.delay(4, function()
        for i, data in ipairs(notifQueue) do
            if data.frame == frame then
                table.remove(notifQueue, i)
                if frame and frame.Parent then
                    local tweenOut = TS:Create(frame, TweenInfo.new(0.3, Enum.EasingStyle.Quint, Enum.EasingDirection.In), {
                        Position = UDim2.new(1,20,1,data.yOffset)
                    })
                    tweenOut:Play()
                    tweenOut.Completed:Connect(function()
                        if frame then frame:Destroy() end
                    end)
                end
                updatePositions()
                break
            end
        end
    end)
end

local function getRoot()local c=pl.Character return c and c:FindFirstChild("HumanoidRootPart")end
local function neonPart(sz,col,trans)local p=Instance.new("Part")p.Size=Vector3.new(sz,sz,sz);p.Shape=Enum.PartType.Ball;p.Material=Enum.Material.Neon;p.Color=col;p.CastShadow=false;p.CanCollide=false;p.Anchored=true;p.Transparency=trans or 0.1;return p end

local globalColor=Color3.fromRGB(80,160,255);local globalColor2=Color3.fromRGB(160,80,255)
local glowEnabled=true;local glowedParts={};local glowConn=nil;local lastGlowTarget=nil

local function clearGlow()for p,o in pairs(glowedParts)do if p and p.Parent then p.Color=o.Color;p.Transparency=o.Transparency end end;glowedParts={};lastGlowTarget=nil;if glowConn then glowConn:Disconnect();glowConn=nil end end

local function applyGlowToModel(model)if not model then return end;local parts={};if model:IsA("BasePart")then table.insert(parts,model)end;for _,v in ipairs(model:GetDescendants())do if v:IsA("BasePart")then table.insert(parts,v)end end;for _,p in ipairs(parts)do if not glowedParts[p]then glowedParts[p]={Color=p.Color,Transparency=p.Transparency}end;p.Color=globalColor;p.Transparency=0.3 end;if glowConn then glowConn:Disconnect()end;glowConn=RS.Heartbeat:Connect(function()for p in pairs(glowedParts)do if p and p.Parent then p.Color=globalColor end end end)end

RS.Heartbeat:Connect(function()if not glowEnabled then if lastGlowTarget then clearGlow()end;return end;if not m then return end;local t=m.Target;local ch=pl.Character;if not t or not t:IsA("BasePart")then if lastGlowTarget then clearGlow()end;return end;if ch and t:IsDescendantOf(ch)then if lastGlowTarget then clearGlow()end;return end;local ign={"KittySnow","KittyTrail","KittyOrbit","KittyCage","KittySparks","KittyRainbow"}for _,f in ipairs(ign)do local fd=workspace:FindFirstChild(f)if fd and t:IsDescendantOf(fd)then return end end;if t.Anchored then if lastGlowTarget then clearGlow()end;return end;local mod=t;local anc=t.Parent;if anc and anc:IsA("Model")and anc~=workspace then mod=anc end;if mod==lastGlowTarget then return end;clearGlow();lastGlowTarget=mod;applyGlowToModel(mod)end)
m.Button1Up:Connect(function()task.delay(0.5,function()if lastGlowTarget then clearGlow()end end)end)

-- Sky & Weather
local function applySky()for _,o in ipairs(L:GetChildren())do if o:IsA("Sky")or o:IsA("Atmosphere")then o:Destroy()end end;local s=Instance.new("Sky",L)s.SkyboxBk="rbxassetid://159454299";s.SkyboxDn="rbxassetid://159454296";s.SkyboxFt="rbxassetid://159454293";s.SkyboxLf="rbxassetid://159454286";s.SkyboxRt="rbxassetid://159454302";s.SkyboxUp="rbxassetid://159454309";local a=Instance.new("Atmosphere",L)a.Density=0.35;a.Offset=0.1;a.Color=Color3.fromRGB(199,215,255);a.Decay=Color3.fromRGB(90,110,160);a.Glare=0.1;a.Haze=1.5;L.Ambient=Color3.fromRGB(160,180,220);L.OutdoorAmbient=Color3.fromRGB(120,150,200);L.FogColor=Color3.fromRGB(180,200,230);L.FogEnd=500;L.FogStart=200;L.Brightness=1.2;L.ClockTime=18;showNotif("Скайбокс применён!",Color3.fromRGB(80,130,200))end
local function setTime(t)L.ClockTime=t;local n={[0]="Ночь",[14]="День",[18]="Закат"};showNotif("Время: "..(n[t] or t),Color3.fromRGB(200,160,60))end
local function setFog(d)L.FogEnd=d;L.FogStart=d*0.4;L.FogColor=Color3.fromRGB(180,200,230);showNotif("Туман включён!",Color3.fromRGB(120,120,180))end
local function removeFog()L.FogEnd=100000;L.FogStart=99000;showNotif("Туман убран!",Color3.fromRGB(100,100,160))end

-- Snow
local snowParts={};local snowActive=false;local snowConn=nil;local snowFolder=Instance.new("Folder",workspace);snowFolder.Name="KittySnow"
local function startSnow()if snowActive then return end;snowActive=true;local spread=160;local height=80;for i=1,600 do local root=getRoot()if not root then break end;local sz=0.35+math.random()*(0.85-0.35);local p=neonPart(sz,Color3.fromRGB(200,225,255),0.1);local rp=root.Position;p.Position=Vector3.new(rp.X+math.random(-spread,spread),rp.Y+math.random(0,height),rp.Z+math.random(-spread,spread));p.Parent=snowFolder;table.insert(snowParts,{part=p,speed=12+math.random()*18})end;snowConn=RS.Heartbeat:Connect(function(dt)if not snowActive then return end;local root=getRoot()if not root then return end;local rpos=root.Position;for _,f in ipairs(snowParts)do local p=f.part;if p and p.Parent then local fp=p.Position;local ny=fp.Y-f.speed*dt;if ny<rpos.Y-12 then p.Position=Vector3.new(rpos.X+math.random(-spread,spread),rpos.Y+height,rpos.Z+math.random(-spread,spread))else p.Position=Vector3.new(fp.X+math.sin(tick()*0.9+fp.X*0.5)*0.4*dt,ny,fp.Z+math.cos(tick()*0.7+fp.Z*0.5)*0.3*dt)end end end end);showNotif("Снег запущен! (600 снежинок)",Color3.fromRGB(100,160,220))end
local function stopSnow()snowActive=false;if snowConn then snowConn:Disconnect();snowConn=nil end;for _,f in ipairs(snowParts)do if f.part and f.part.Parent then f.part:Destroy()end end;snowParts={};showNotif("Снег остановлен!",Color3.fromRGB(90,90,150))end

-- Rain
local function setRain()stopSnow();local ch=pl.Character;local root=ch and ch:FindFirstChild("HumanoidRootPart");if not root then return end;local em=Instance.new("Part");em.Size=Vector3.new(80,1,80);em.Anchored=true;em.CanCollide=false;em.Transparency=1;em.Position=root.Position+Vector3.new(0,40,0);em.Name="KittyRain";em.Parent=workspace;local pe=Instance.new("ParticleEmitter",em);pe.Texture="rbxassetid://241922778";pe.Rate=500;pe.Lifetime=NumberRange.new(1.5,2.5);pe.Speed=NumberRange.new(70,90);pe.EmissionDirection=Enum.NormalId.Bottom;pe.Transparency=NumberSequence.new(0.35);pe.Size=NumberSequence.new({NumberSequenceKeypoint.new(0,0.06),NumberSequenceKeypoint.new(1,0.02)});showNotif("Дождь запущен!",Color3.fromRGB(60,120,200))end
local function stopRain()local rp=workspace:FindFirstChild("KittyRain");if rp then rp:Destroy()end;showNotif("Дождь остановлен!",Color3.fromRGB(60,90,140))end

-- Orbit
local orbitActive=false;local orbitConn=nil;local orbitFolder=Instance.new("Folder",workspace);orbitFolder.Name="KittyOrbit";local orbitParts={}
local function startOrbit(cA,cB,lbl)if orbitConn then orbitConn:Disconnect();orbitConn=nil end;for _,p in ipairs(orbitParts)do if p and p.Parent then p:Destroy()end end;orbitParts={};orbitActive=true;cA=cA or globalColor;cB=cB or globalColor2;local COUNT=80;local RADIUS=8;for i=1,COUNT do local p=Instance.new("Part");p.Size=Vector3.new(0.55,0.55,0.55);p.Shape=Enum.PartType.Ball;p.Material=Enum.Material.Neon;p.Color=cA;p.CastShadow=false;p.CanCollide=false;p.Anchored=true;p.Transparency=0.05;p.Parent=orbitFolder;table.insert(orbitParts,p)end;local TAIL=20;for i=1,TAIL do local p=Instance.new("Part");local sz=0.9*(1-i/TAIL)+0.15;p.Size=Vector3.new(sz,sz,sz);p.Shape=Enum.PartType.Ball;p.Material=Enum.Material.Neon;p.Color=cB;p.CastShadow=false;p.CanCollide=false;p.Anchored=true;p.Transparency=0.0;p.Parent=orbitFolder;table.insert(orbitParts,p)end;local t0=tick();orbitConn=RS.Heartbeat:Connect(function()local root=getRoot()if not root then return end;local pos=root.Position;local t=(tick()-t0);local sp=1.4;for i,p in ipairs(orbitParts)do if i>COUNT then break end;if p and p.Parent then local ang=(i/COUNT)*math.pi*2+t*sp;local x=math.cos(ang)*RADIUS;local y=math.sin(ang)*RADIUS*0.35+math.sin(t*0.5)*0.8;local z=math.sin(ang)*RADIUS;p.Position=Vector3.new(pos.X+x,pos.Y+y,pos.Z+z);local mix=(math.sin(t*2+i*0.2)+1)/2;p.Color=Color3.new(cA.R+(cB.R-cA.R)*mix,cA.G+(cB.G-cA.G)*mix,cA.B+(cB.B-cA.B)*mix);local pls=0.45+math.sin(t*3+i*0.15)*0.1;p.Size=Vector3.new(pls,pls,pls)end end;local headAng=t*sp;for j=1,TAIL do local idx=COUNT+j;local p=orbitParts[idx];if p and p.Parent then local a=headAng-j*0.12;local x=math.cos(a)*RADIUS;local y=math.sin(a)*RADIUS*0.35+math.sin(t*0.5)*0.8;local z=math.sin(a)*RADIUS;p.Position=Vector3.new(pos.X+x,pos.Y+y,pos.Z+z);local fade=1-(j/TAIL);p.Transparency=1-fade*0.95;local sz=(0.9*fade)+0.1;p.Size=Vector3.new(sz,sz,sz);p.Color=cB end end end);showNotif(lbl or "Орбита включена!",cA)end
local function stopOrbit()orbitActive=false;if orbitConn then orbitConn:Disconnect();orbitConn=nil end;for _,p in ipairs(orbitParts)do if p and p.Parent then p:Destroy()end end;orbitParts={};showNotif("Орбита выключена!",Color3.fromRGB(80,80,140))end

-- Trail
local trailActive=false;local trailObj=nil;local att0,att1,trailConn=nil
local function startTrail(cA,cB,lbl)if trailObj then trailObj:Destroy();trailObj=nil end;if att0 then att0:Destroy();att0=nil end;if att1 then att1:Destroy();att1=nil end;if trailConn then trailConn:Disconnect();trailConn=nil end;trailActive=true;cA=cA or globalColor;cB=cB or globalColor2;local function attach()local ch=pl.Character;if not ch then return end;local root=ch:FindFirstChild("HumanoidRootPart");if not root then return end;att0=Instance.new("Attachment",root);att0.Position=Vector3.new(0,1,0);att1=Instance.new("Attachment",root);att1.Position=Vector3.new(0,-1,0);trailObj=Instance.new("Trail",root);trailObj.Attachment0=att0;trailObj.Attachment1=att1;trailObj.Lifetime=0.8;trailObj.MinLength=0;trailObj.FaceCamera=true;trailObj.LightEmission=1;trailObj.LightInfluence=0;trailObj.Color=ColorSequence.new({ColorSequenceKeypoint.new(0,cA),ColorSequenceKeypoint.new(1,cB)});trailObj.Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0),NumberSequenceKeypoint.new(1,1)});trailObj.WidthScale=NumberSequence.new({NumberSequenceKeypoint.new(0,1),NumberSequenceKeypoint.new(1,0)})end;attach();trailConn=pl.CharacterAdded:Connect(function()task.wait(0.5);if trailActive then attach()end end);showNotif(lbl or "След включён!",cA)end
local function stopTrail()trailActive=false;if trailObj then trailObj:Destroy();trailObj=nil end;if att0 then att0:Destroy();att0=nil end;if att1 then att1:Destroy();att1=nil end;if trailConn then trailConn:Disconnect();trailConn=nil end;showNotif("След выключен!",Color3.fromRGB(70,90,150))end

-- Rainbow
local rainbowActive=false;local rainbowConn=nil;local rainbowFolder=Instance.new("Folder",workspace);rainbowFolder.Name="KittyRainbow";local rainbowParts={}
local function startRainbow()if rainbowActive then return end;rainbowActive=true;rainbowConn=RS.Heartbeat:Connect(function(dt)local root=getRoot()if not root then return end;local pos=root.Position;local h=(tick()*0.4)%1;local p=Instance.new("Part");p.Size=Vector3.new(0.8,0.12,0.8);p.Material=Enum.Material.Neon;p.Color=Color3.fromHSV(h,1,1);p.CastShadow=false;p.CanCollide=false;p.Anchored=true;p.Transparency=0.05;p.Position=Vector3.new(pos.X+math.random(-10,10)*0.1,pos.Y-2.8,pos.Z+math.random(-10,10)*0.1);p.Parent=rainbowFolder;table.insert(rainbowParts,{part=p,born=tick()});local now=tick();for i=#rainbowParts,1,-1 do local rp=rainbowParts[i];if rp.part and rp.part.Parent then local age=now-rp.born;if age>0.8 then rp.part:Destroy();table.remove(rainbowParts,i)else rp.part.Transparency=0.05+(age/0.8)*0.95;local s=0.8+age*1.2;rp.part.Size=Vector3.new(s,0.12,s)end else table.remove(rainbowParts,i)end end end);showNotif("Радуга под ногами включена!",Color3.fromRGB(255,120,200))end
local function stopRainbow()rainbowActive=false;if rainbowConn then rainbowConn:Disconnect();rainbowConn=nil end;for _,rp in ipairs(rainbowParts)do if rp.part and rp.part.Parent then rp.part:Destroy()end end;rainbowParts={};showNotif("Радуга выключена!",Color3.fromRGB(140,80,150))end

-- Cage
local cageActive=false;local cageConn=nil;local cageFolder=Instance.new("Folder",workspace);cageFolder.Name="KittyCage";local cageParts={}
local function startCage(col,lbl)if cageConn then cageConn:Disconnect();cageConn=nil end;for _,p in ipairs(cageParts)do if p and p.Parent then p:Destroy()end end;cageParts={};cageActive=true;col=col or globalColor;local rings={{axis="X",offset=0},{axis="Y",offset=math.pi/3},{axis="Z",offset=math.pi*2/3}};local COUNT=30;local RADIUS=4.5;for _,ring in ipairs(rings)do for i=1,COUNT do local p=neonPart(0.3,col,0.05);p.Parent=cageFolder;table.insert(cageParts,{part=p,ring=ring,idx=i,total=COUNT})end end;local t0=tick();cageConn=RS.Heartbeat:Connect(function()local root=getRoot()if not root then return end;local pos=root.Position;local t=(tick()-t0)*1.1;for _,cp in ipairs(cageParts)do if cp.part and cp.part.Parent then local ang=(cp.idx/cp.total)*math.pi*2+t+cp.ring.offset;local x,y,z=0,0,0;if cp.ring.axis=="X" then y=math.cos(ang)*RADIUS;z=math.sin(ang)*RADIUS elseif cp.ring.axis=="Y" then x=math.cos(ang)*RADIUS;z=math.sin(ang)*RADIUS else x=math.cos(ang)*RADIUS;y=math.sin(ang)*RADIUS end;cp.part.Position=Vector3.new(pos.X+x,pos.Y+y,pos.Z+z);local mix=(math.sin(t*2+cp.idx*0.3)+1)/2;cp.part.Color=Color3.new(col.R*mix+1*(1-mix),col.G*mix+1*(1-mix),col.B*mix+0.3*(1-mix))end end end);showNotif(lbl or "Кристальная клетка включена!",col)end
local function stopCage()cageActive=false;if cageConn then cageConn:Disconnect();cageConn=nil end;for _,p in ipairs(cageParts)do if p and p.Parent then p:Destroy()end end;cageParts={};showNotif("Клетка выключена!",Color3.fromRGB(0,150,200))end

-- Sparks
local sparkActive=false;local sparkConn=nil;local sparkFolder=Instance.new("Folder",workspace);sparkFolder.Name="KittySparks";local sparkParts={}
local function startSparks(col,lbl,rainbow)if sparkConn then sparkConn:Disconnect();sparkConn=nil end;for _,sp in ipairs(sparkParts)do if sp.part and sp.part.Parent then sp.part:Destroy()end end;sparkParts={};sparkActive=true;col=col or globalColor;sparkConn=RS.Heartbeat:Connect(function(dt)local root=getRoot()if not root then return end;local pos=root.Position;local useCol=rainbow and Color3.fromHSV((tick()*0.5)%1,1,1)or col;for i=1,3 do local p=neonPart(0.18,useCol,0.0);p.Position=pos+Vector3.new(0,1,0);p.Parent=sparkFolder;local dir=Vector3.new(math.random(-100,100)/100,math.random(20,100)/100,math.random(-100,100)/100).Unit;table.insert(sparkParts,{part=p,born=tick(),vel=dir*(8+math.random()*14)})end;local now=tick();for i=#sparkParts,1,-1 do local sp=sparkParts[i];if sp.part and sp.part.Parent then local age=now-sp.born;local life=0.75;if age>life then sp.part:Destroy();table.remove(sparkParts,i)else local t=age/life;sp.vel=sp.vel+Vector3.new(0,-18*dt,0);sp.part.Position=sp.part.Position+sp.vel*dt;sp.part.Transparency=t*0.97;local s=0.18*(1-t*0.8);sp.part.Size=Vector3.new(s,s,s)end else table.remove(sparkParts,i)end end end);showNotif(lbl or "Искры включены!",col)end
local function stopSparks()sparkActive=false;if sparkConn then sparkConn:Disconnect();sparkConn=nil end;for _,sp in ipairs(sparkParts)do if sp.part and sp.part.Parent then sp.part:Destroy()end end;sparkParts={};showNotif("Искры выключены!",Color3.fromRGB(150,120,0))end

local function stopAll()stopOrbit();stopTrail();stopRainbow();stopCage();stopSparks();stopSnow();stopRain();showNotif("Все эффекты выключены!",Color3.fromRGB(150,80,80))end

-- GUI
local sg=Instance.new("ScreenGui",pg);sg.Name="KittyGui";sg.ResetOnSpawn=false;sg.ZIndexBehavior=Enum.ZIndexBehavior.Sibling;sg.DisplayOrder=999
local main=Instance.new("Frame",sg);main.Size=UDim2.new(0,545,0,400);main.Position=UDim2.new(0.5,-272,0.5,-200);main.BackgroundColor3=Color3.fromRGB(10,9,18);main.BorderSizePixel=0;main.Active=true;main.Draggable=true;main.Visible=true;Instance.new("UICorner",main).CornerRadius=UDim.new(0,12);local ms=Instance.new("UIStroke",main);ms.Color=Color3.fromRGB(75,65,175);ms.Thickness=1;ms.Transparency=0.3
local titleBar=Instance.new("Frame",main);titleBar.Size=UDim2.new(1,0,0,44);titleBar.BackgroundColor3=Color3.fromRGB(13,11,26);titleBar.BorderSizePixel=0;Instance.new("UICorner",titleBar).CornerRadius=UDim.new(0,12)
local titleTxt=Instance.new("TextLabel",titleBar);titleTxt.Size=UDim2.new(1,-100,1,0);titleTxt.Position=UDim2.new(0,16,0,0);titleTxt.BackgroundTransparency=1;titleTxt.Text="Kitty Script";titleTxt.TextColor3=Color3.fromRGB(210,205,255);titleTxt.TextSize=16;titleTxt.Font=Enum.Font.GothamBold;titleTxt.TextXAlignment=Enum.TextXAlignment.Left;titleTxt.ZIndex=3
local function makeTBtn(ofx,bg,txt)local b=Instance.new("TextButton",titleBar);b.Size=UDim2.new(0,28,0,28);b.Position=UDim2.new(1,ofx,0.5,-14);b.BackgroundColor3=bg;b.Text=txt;b.TextColor3=Color3.fromRGB(255,255,255);b.TextSize=14;b.Font=Enum.Font.GothamBold;b.BorderSizePixel=0;b.ZIndex=4;Instance.new("UICorner",b).CornerRadius=UDim.new(0,7);return b end
local closeBtn=makeTBtn(-36,Color3.fromRGB(145,32,32),"x");local minBtn=makeTBtn(-70,Color3.fromRGB(42,38,98),"-")
local navPanel=Instance.new("Frame",main);navPanel.Size=UDim2.new(0,152,1,-44);navPanel.Position=UDim2.new(0,0,0,44);navPanel.BackgroundColor3=Color3.fromRGB(12,10,22);navPanel.BorderSizePixel=0;local navLayout=Instance.new("UIListLayout",navPanel);navLayout.Padding=UDim.new(0,0);navLayout.SortOrder=Enum.SortOrder.LayoutOrder
local divLine=Instance.new("Frame",main);divLine.Size=UDim2.new(0,1,1,-44);divLine.Position=UDim2.new(0,152,0,44);divLine.BackgroundColor3=Color3.fromRGB(38,35,78);divLine.BorderSizePixel=0
local contentArea=Instance.new("Frame",main);contentArea.Size=UDim2.new(1,-152,1,-44);contentArea.Position=UDim2.new(0,152,0,44);contentArea.BackgroundColor3=Color3.fromRGB(15,13,28);contentArea.BorderSizePixel=0
local avaFrame=Instance.new("Frame",navPanel);avaFrame.Size=UDim2.new(1,0,0,50);avaFrame.LayoutOrder=99;avaFrame.BackgroundColor3=Color3.fromRGB(10,8,20);avaFrame.BorderSizePixel=0;local avaIco=Instance.new("TextLabel",avaFrame);avaIco.Size=UDim2.new(0,28,0,28);avaIco.Position=UDim2.new(0,8,0.5,-14);avaIco.BackgroundColor3=Color3.fromRGB(58,48,138);avaIco.BorderSizePixel=0;avaIco.Text=string.sub(pl.Name,1,1):upper();avaIco.TextColor3=Color3.fromRGB(210,205,255);avaIco.TextSize=13;avaIco.Font=Enum.Font.GothamBold;Instance.new("UICorner",avaIco).CornerRadius=UDim.new(1,0);local avaName=Instance.new("TextLabel",avaFrame);avaName.Size=UDim2.new(1,-44,1,0);avaName.Position=UDim2.new(0,42,0,0);avaName.BackgroundTransparency=1;avaName.Text=pl.Name;avaName.TextColor3=Color3.fromRGB(135,130,195);avaName.TextSize=12;avaName.Font=Enum.Font.Gotham;avaName.TextXAlignment=Enum.TextXAlignment.Left

local pages={}
local function makePage(name)local pg=Instance.new("ScrollingFrame",contentArea);pg.Size=UDim2.new(1,0,1,0);pg.BackgroundTransparency=1;pg.BorderSizePixel=0;pg.ScrollBarThickness=3;pg.ScrollBarImageColor3=Color3.fromRGB(75,70,145);pg.CanvasSize=UDim2.new(0,0,0,0);pg.Visible=false;local l=Instance.new("UIListLayout",pg);l.SortOrder=Enum.SortOrder.LayoutOrder;l:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()pg.CanvasSize=UDim2.new(0,0,0,l.AbsoluteContentSize.Y+16)end);pages[name]=pg;return pg end
local function makeSection(page,title,order)local hdr=Instance.new("TextLabel",page);hdr.Size=UDim2.new(1,0,0,26);hdr.BackgroundTransparency=1;hdr.Text=title;hdr.TextColor3=Color3.fromRGB(90,85,155);hdr.TextSize=10;hdr.Font=Enum.Font.GothamBold;hdr.TextXAlignment=Enum.TextXAlignment.Left;hdr.LayoutOrder=order;local pad=Instance.new("UIPadding",hdr);pad.PaddingLeft=UDim.new(0,14);pad.PaddingTop=UDim.new(0,8)end
local function makeActionBtn(page,label,order)local row=Instance.new("Frame",page);row.Size=UDim2.new(1,0,0,40);row.BackgroundColor3=Color3.fromRGB(19,17,34);row.BorderSizePixel=0;row.LayoutOrder=order;local div=Instance.new("Frame",row);div.Size=UDim2.new(1,0,0,1);div.Position=UDim2.new(0,0,1,-1);div.BackgroundColor3=Color3.fromRGB(30,28,55);div.BorderSizePixel=0;local lbl=Instance.new("TextLabel",row);lbl.Size=UDim2.new(1,-46,1,0);lbl.Position=UDim2.new(0,14,0,0);lbl.BackgroundTransparency=1;lbl.Text=label;lbl.TextColor3=Color3.fromRGB(198,195,245);lbl.TextSize=13;lbl.Font=Enum.Font.Gotham;lbl.TextXAlignment=Enum.TextXAlignment.Left;local btn=Instance.new("TextButton",row);btn.Size=UDim2.new(0,22,0,22);btn.Position=UDim2.new(1,-30,0.5,-11);btn.BackgroundColor3=Color3.fromRGB(45,40,105);btn.Text=">";btn.TextColor3=Color3.fromRGB(170,165,245);btn.TextSize=12;btn.Font=Enum.Font.GothamBold;btn.BorderSizePixel=0;Instance.new("UICorner",btn).CornerRadius=UDim.new(0,6);row.MouseEnter:Connect(function()TS:Create(row,TweenInfo.new(0.1),{BackgroundColor3=Color3.fromRGB(28,25,48)}):Play()end);row.MouseLeave:Connect(function()TS:Create(row,TweenInfo.new(0.1),{BackgroundColor3=Color3.fromRGB(19,17,34)}):Play()end);return btn end

-- Pages content
local pgSky=makePage("sky");makeSection(pgSky,"СКАЙБОКС",1);local bSky=makeActionBtn(pgSky,"Применить красивое небо",2);local bDay=makeActionBtn(pgSky,"День (14:00)",3);local bSunset=makeActionBtn(pgSky,"Закат (18:00)",4);local bNight=makeActionBtn(pgSky,"Ночь (0:00)",5);makeSection(pgSky,"АТМОСФЕРА",6);local bFogOn=makeActionBtn(pgSky,"Включить туман",7);local bFogOff=makeActionBtn(pgSky,"Убрать туман",8);bSky.MouseButton1Click:Connect(applySky);bDay.MouseButton1Click:Connect(function()setTime(14)end);bSunset.MouseButton1Click:Connect(function()setTime(18)end);bNight.MouseButton1Click:Connect(function()setTime(0)end);bFogOn.MouseButton1Click:Connect(function()setFog(200)end);bFogOff.MouseButton1Click:Connect(removeFog)
local pgWeather=makePage("weather");makeSection(pgWeather,"СНЕГ",1);local bSnowOn=makeActionBtn(pgWeather,"Запустить снег (600шт)",2);local bSnowOff=makeActionBtn(pgWeather,"Остановить снег",3);makeSection(pgWeather,"ДОЖДЬ",4);local bRainOn=makeActionBtn(pgWeather,"Запустить дождь",5);local bRainOff=makeActionBtn(pgWeather,"Остановить дождь",6);bSnowOn.MouseButton1Click:Connect(startSnow);bSnowOff.MouseButton1Click:Connect(stopSnow);bRainOn.MouseButton1Click:Connect(setRain);bRainOff.MouseButton1Click:Connect(stopRain)
local pgVisual=makePage("visual");makeSection(pgVisual,"ОРБИТА",1);local bOrbGreen=makeActionBtn(pgVisual,"Зеленая орбита",2);local bOrbBlue=makeActionBtn(pgVisual,"Синяя орбита",3);local bOrbFire=makeActionBtn(pgVisual,"Огненная орбита",4);local bOrbCyan=makeActionBtn(pgVisual,"Cyan орбита",5);local bOrbOff=makeActionBtn(pgVisual,"Орбита ВЫКЛ",6);makeSection(pgVisual,"СЛЕД",7);local bTrailBlue=makeActionBtn(pgVisual,"Синий след",8);local bTrailFire=makeActionBtn(pgVisual,"Огненный след",9);local bTrailRainbow=makeActionBtn(pgVisual,"Радужный след",10);local bTrailOff=makeActionBtn(pgVisual,"След ВЫКЛ",11);makeSection(pgVisual,"КОЛЬЦА",12);local bCageBlue=makeActionBtn(pgVisual,"Синяя клетка",13);local bCagePink=makeActionBtn(pgVisual,"Розовая клетка",14);local bCageOff=makeActionBtn(pgVisual,"Клетка ВЫКЛ",15);makeSection(pgVisual,"ИСКРЫ",16);local bSparkGold=makeActionBtn(pgVisual,"Золотые искры",17);local bSparkBlue=makeActionBtn(pgVisual,"Синие искры",18);local bSparkRainbow=makeActionBtn(pgVisual,"Радужные искры",19);local bSparkOff=makeActionBtn(pgVisual,"Искры ВЫКЛ",20);makeSection(pgVisual,"ПОД НОГАМИ",21);local bRainbowOn=makeActionBtn(pgVisual,"Радуга ВКЛ",22);local bRainbowOff=makeActionBtn(pgVisual,"Радуга ВЫКЛ",23);makeSection(pgVisual,"РАСТЯЖКА GUI",24)
local stretchRow=Instance.new("Frame",pgVisual);stretchRow.Size=UDim2.new(1,0,0,48);stretchRow.BackgroundColor3=Color3.fromRGB(19,17,34);stretchRow.BorderSizePixel=0;stretchRow.LayoutOrder=24;local stretchLbl=Instance.new("TextLabel",stretchRow);stretchLbl.Size=UDim2.new(0.6,0,1,0);stretchLbl.Position=UDim2.new(0,14,0,0);stretchLbl.BackgroundTransparency=1;stretchLbl.Text="Масштаб GUI";stretchLbl.TextColor3=Color3.fromRGB(198,195,245);stretchLbl.TextSize=13;stretchLbl.Font=Enum.Font.Gotham;stretchLbl.TextXAlignment=Enum.TextXAlignment.Left;local stretchVal=Instance.new("TextLabel",stretchRow);stretchVal.Size=UDim2.new(0.3,-14,1,0);stretchVal.Position=UDim2.new(0.6,0,0,0);stretchVal.BackgroundTransparency=1;stretchVal.Text="100%";stretchVal.TextColor3=Color3.fromRGB(80,160,255);stretchVal.TextSize=13;stretchVal.Font=Enum.Font.GothamBold;stretchVal.TextXAlignment=Enum.TextXAlignment.Right;local stretchTrack=Instance.new("Frame",stretchRow);stretchTrack.Size=UDim2.new(1,-28,0,6);stretchTrack.Position=UDim2.new(0,14,0,30);stretchTrack.BackgroundColor3=Color3.fromRGB(35,32,65);stretchTrack.BorderSizePixel=0;Instance.new("UICorner",stretchTrack).CornerRadius=UDim.new(1,0);local stretchFill=Instance.new("Frame",stretchTrack);stretchFill.Size=UDim2.new(1,0,1,0);stretchFill.BackgroundColor3=Color3.fromRGB(40,100,255);stretchFill.BorderSizePixel=0;Instance.new("UICorner",stretchFill).CornerRadius=UDim.new(1,0);local stretchKnob=Instance.new("Frame",stretchTrack);stretchKnob.Size=UDim2.new(0,16,0,16);stretchKnob.Position=UDim2.new(1,-8,0.5,-8);stretchKnob.BackgroundColor3=Color3.fromRGB(80,150,255);stretchKnob.BorderSizePixel=0;Instance.new("UICorner",stretchKnob).CornerRadius=UDim.new(1,0);local uiScale=Instance.new("UIScale",sg);uiScale.Scale=1;local function setUIScale(val)val=math.clamp(val,0.5,1.5);local alpha=(val-0.5)/(1.5-0.5);stretchFill.Size=UDim2.new(alpha,0,1,0);stretchKnob.Position=UDim2.new(alpha,-8,0.5,-8);stretchVal.Text=tostring(math.floor(val*100)).."%";uiScale.Scale=val end;setUIScale(1);local dragStretch=false;stretchTrack.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dragStretch=true;local a=(i.Position.X-stretchTrack.AbsolutePosition.X)/stretchTrack.AbsoluteSize.X;local newVal=0.5+a*(1.5-0.5);setUIScale(newVal)end end);stretchKnob.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dragStretch=true end end);UIS.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dragStretch=false end end);UIS.InputChanged:Connect(function(i)if dragStretch and i.UserInputType==Enum.UserInputType.MouseMovement then local a=(i.Position.X-stretchTrack.AbsolutePosition.X)/stretchTrack.AbsoluteSize.X;local newVal=0.5+a*(1.5-0.5);setUIScale(newVal)end end)
makeSection(pgVisual,"СБРОС",25);local bStopAll=makeActionBtn(pgVisual,"Выключить ВСЕ",26)
bOrbGreen.MouseButton1Click:Connect(function()startOrbit(Color3.fromRGB(100,255,80),Color3.fromRGB(200,255,120),"Зеленая орбита!")end);bOrbBlue.MouseButton1Click:Connect(function()startOrbit(Color3.fromRGB(80,160,255),Color3.fromRGB(160,80,255),"Синяя орбита!")end);bOrbFire.MouseButton1Click:Connect(function()startOrbit(Color3.fromRGB(255,80,20),Color3.fromRGB(255,220,30),"Огненная орбита!")end);bOrbCyan.MouseButton1Click:Connect(function()startOrbit(Color3.fromRGB(0,220,220),Color3.fromRGB(0,255,180),"Cyan орбита!")end);bOrbOff.MouseButton1Click:Connect(stopOrbit)
bTrailBlue.MouseButton1Click:Connect(function()startTrail(Color3.fromRGB(80,160,255),Color3.fromRGB(160,80,255),"Синий след!")end);bTrailFire.MouseButton1Click:Connect(function()startTrail(Color3.fromRGB(255,120,20),Color3.fromRGB(255,220,0),"Огненный след!")end);bTrailRainbow.MouseButton1Click:Connect(function()startTrail(Color3.fromRGB(255,80,200),Color3.fromRGB(80,200,255),"Радужный след!")end);bTrailOff.MouseButton1Click:Connect(stopTrail)
bCageBlue.MouseButton1Click:Connect(function()startCage(Color3.fromRGB(0,200,255),"Синяя клетка!")end);bCagePink.MouseButton1Click:Connect(function()startCage(Color3.fromRGB(255,80,200),"Розовая клетка!")end);bCageOff.MouseButton1Click:Connect(stopCage)
bSparkGold.MouseButton1Click:Connect(function()startSparks(Color3.fromRGB(255,200,0),"Золотые искры!")end);bSparkBlue.MouseButton1Click:Connect(function()startSparks(Color3.fromRGB(80,160,255),"Синие искры!")end);bSparkRainbow.MouseButton1Click:Connect(function()startSparks(nil,"Радужные искры!",true)end);bSparkOff.MouseButton1Click:Connect(stopSparks)
bRainbowOn.MouseButton1Click:Connect(startRainbow);bRainbowOff.MouseButton1Click:Connect(stopRainbow);bStopAll.MouseButton1Click:Connect(stopAll)
local pgMisc=makePage("misc");makeSection(pgMisc,"МЫШЬ",1);local bUnlock=makeActionBtn(pgMisc,"Разблокировать мышь",2);local bHide=makeActionBtn(pgMisc,"Скрыть курсор",3);local bShow=makeActionBtn(pgMisc,"Показать курсор",4);makeSection(pgMisc,"СВЕЧЕНИЕ ПРЕДМЕТОВ",5);local glowToggleRow=Instance.new("Frame",pgMisc);glowToggleRow.Size=UDim2.new(1,0,0,40);glowToggleRow.BackgroundColor3=Color3.fromRGB(19,17,34);glowToggleRow.BorderSizePixel=0;glowToggleRow.LayoutOrder=6;local glowLbl=Instance.new("TextLabel",glowToggleRow);glowLbl.Size=UDim2.new(1,-60,1,0);glowLbl.Position=UDim2.new(0,14,0,0);glowLbl.BackgroundTransparency=1;glowLbl.Text="Плотная тонировка (прозр. 0.3)";glowLbl.TextColor3=Color3.fromRGB(198,195,245);glowLbl.TextSize=13;glowLbl.Font=Enum.Font.Gotham;glowLbl.TextXAlignment=Enum.TextXAlignment.Left;local glowToggleBtn=Instance.new("TextButton",glowToggleRow);glowToggleBtn.Size=UDim2.new(0,40,0,22);glowToggleBtn.Position=UDim2.new(1,-50,0.5,-11);glowToggleBtn.BorderSizePixel=0;glowToggleBtn.Font=Enum.Font.GothamBold;glowToggleBtn.TextSize=10;Instance.new("UICorner",glowToggleBtn).CornerRadius=UDim.new(0,11);local function updateGlowBtn()if glowEnabled then glowToggleBtn.BackgroundColor3=Color3.fromRGB(40,100,255);glowToggleBtn.TextColor3=Color3.fromRGB(255,255,255);glowToggleBtn.Text="ON"else glowToggleBtn.BackgroundColor3=Color3.fromRGB(45,40,70);glowToggleBtn.TextColor3=Color3.fromRGB(130,125,180);glowToggleBtn.Text="OFF";clearGlow()end end;updateGlowBtn();glowToggleBtn.MouseButton1Click:Connect(function()glowEnabled=not glowEnabled;updateGlowBtn();showNotif("Тонировка: "..(glowEnabled and "ON" or "OFF"),glowEnabled and Color3.fromRGB(40,100,255)or Color3.fromRGB(80,80,130))end);bUnlock.MouseButton1Click:Connect(function()UIS.MouseBehavior=Enum.MouseBehavior.Default;showNotif("Мышь разблокирована!",Color3.fromRGB(80,200,120))end);bHide.MouseButton1Click:Connect(function()UIS.MouseIconEnabled=false;showNotif("Курсор скрыт!",Color3.fromRGB(130,100,200))end);bShow.MouseButton1Click:Connect(function()UIS.MouseIconEnabled=true;showNotif("Курсор показан!",Color3.fromRGB(130,100,200))end)

-- Global color apply (no GUI recolor)
local function applyGlobalColor()if orbitActive then startOrbit(globalColor,globalColor2,"Орбита обновлена!")end;if trailActive then startTrail(globalColor,globalColor2,"След обновлён!")end;if cageActive then startCage(globalColor,"Клетка обновлена!")end;if sparkActive then startSparks(globalColor,"Искры обновлены!")end;clearGlow();if lastGlowTarget then applyGlowToModel(lastGlowTarget)end;showNotif("Цвет эффектов изменён!",globalColor)end

-- FOV page
local pgFov=makePage("fov");local curFOV=cam.FieldOfView
local fovLabelRow=Instance.new("Frame",pgFov);fovLabelRow.Size=UDim2.new(1,0,0,32);fovLabelRow.BackgroundColor3=Color3.fromRGB(15,13,28);fovLabelRow.BorderSizePixel=0;fovLabelRow.LayoutOrder=1;local fovNameLbl=Instance.new("TextLabel",fovLabelRow);fovNameLbl.Size=UDim2.new(0.6,0,1,0);fovNameLbl.Position=UDim2.new(0,14,0,0);fovNameLbl.BackgroundTransparency=1;fovNameLbl.Text="Field of View";fovNameLbl.TextColor3=Color3.fromRGB(140,135,200);fovNameLbl.TextSize=13;fovNameLbl.Font=Enum.Font.GothamBold;fovNameLbl.TextXAlignment=Enum.TextXAlignment.Left;local fovValLbl=Instance.new("TextLabel",fovLabelRow);fovValLbl.Size=UDim2.new(0.4,-14,1,0);fovValLbl.Position=UDim2.new(0.6,0,0,0);fovValLbl.BackgroundTransparency=1;fovValLbl.Text=tostring(math.round(curFOV)).."°";fovValLbl.TextColor3=Color3.fromRGB(80,160,255);fovValLbl.TextSize=14;fovValLbl.Font=Enum.Font.GothamBold;fovValLbl.TextXAlignment=Enum.TextXAlignment.Right
local sliderRow=Instance.new("Frame",pgFov);sliderRow.Size=UDim2.new(1,0,0,48);sliderRow.BackgroundColor3=Color3.fromRGB(19,17,34);sliderRow.BorderSizePixel=0;sliderRow.LayoutOrder=2;local fovMinLbl=Instance.new("TextLabel",sliderRow);fovMinLbl.Size=UDim2.new(0,30,0,16);fovMinLbl.Position=UDim2.new(0,14,0,4);fovMinLbl.BackgroundTransparency=1;fovMinLbl.Text="30";fovMinLbl.TextColor3=Color3.fromRGB(90,85,140);fovMinLbl.TextSize=10;fovMinLbl.Font=Enum.Font.Gotham;fovMinLbl.TextXAlignment=Enum.TextXAlignment.Left;local fovMaxLbl=Instance.new("TextLabel",sliderRow);fovMaxLbl.Size=UDim2.new(0,40,0,16);fovMaxLbl.Position=UDim2.new(1,-54,0,4);fovMaxLbl.BackgroundTransparency=1;fovMaxLbl.Text="120";fovMaxLbl.TextColor3=Color3.fromRGB(90,85,140);fovMaxLbl.TextSize=10;fovMaxLbl.Font=Enum.Font.Gotham;fovMaxLbl.TextXAlignment=Enum.TextXAlignment.Right;local trackBg=Instance.new("Frame",sliderRow);trackBg.Size=UDim2.new(1,-28,0,6);trackBg.Position=UDim2.new(0,14,0,30);trackBg.BackgroundColor3=Color3.fromRGB(35,32,65);trackBg.BorderSizePixel=0;Instance.new("UICorner",trackBg).CornerRadius=UDim.new(1,0);local trackFill=Instance.new("Frame",trackBg);trackFill.Size=UDim2.new(0,0,1,0);trackFill.BackgroundColor3=Color3.fromRGB(40,100,255);trackFill.BorderSizePixel=0;Instance.new("UICorner",trackFill).CornerRadius=UDim.new(1,0);local sliderKnob=Instance.new("Frame",trackBg);sliderKnob.Size=UDim2.new(0,16,0,16);sliderKnob.Position=UDim2.new(0,-8,0.5,-8);sliderKnob.BackgroundColor3=Color3.fromRGB(80,150,255);sliderKnob.BorderSizePixel=0;Instance.new("UICorner",sliderKnob).CornerRadius=UDim.new(1,0)
local FOV_MIN=30;local FOV_MAX=120;local function fovToAlpha(f)return (f-FOV_MIN)/(FOV_MAX-FOV_MIN)end;local function alphaToFov(a)return math.round(FOV_MIN+a*(FOV_MAX-FOV_MIN))end;local function setSliderAlpha(a)a=math.clamp(a,0,1);trackFill.Size=UDim2.new(a,0,1,0);sliderKnob.Position=UDim2.new(a,-8,0.5,-8);curFOV=alphaToFov(a);fovValLbl.Text=tostring(curFOV).."°"end;setSliderAlpha(fovToAlpha(curFOV));local draggingFov=false;trackBg.InputBegan:Connect(function(inp)if inp.UserInputType==Enum.UserInputType.MouseButton1 then draggingFov=true;setSliderAlpha((inp.Position.X-trackBg.AbsolutePosition.X)/trackBg.AbsoluteSize.X)end end);sliderKnob.InputBegan:Connect(function(inp)if inp.UserInputType==Enum.UserInputType.MouseButton1 then draggingFov=true end end);UIS.InputEnded:Connect(function(inp)if inp.UserInputType==Enum.UserInputType.MouseButton1 then draggingFov=false end end);UIS.InputChanged:Connect(function(inp)if draggingFov and inp.UserInputType==Enum.UserInputType.MouseMovement then setSliderAlpha((inp.Position.X-trackBg.AbsolutePosition.X)/trackBg.AbsoluteSize.X)end end)
local fovApplyRow=Instance.new("Frame",pgFov);fovApplyRow.Size=UDim2.new(1,0,0,48);fovApplyRow.BackgroundColor3=Color3.fromRGB(15,13,28);fovApplyRow.BorderSizePixel=0;fovApplyRow.LayoutOrder=3;local applyFovBtn=Instance.new("TextButton",fovApplyRow);applyFovBtn.Size=UDim2.new(1,-28,0,30);applyFovBtn.Position=UDim2.new(0,14,0.5,-15);applyFovBtn.BackgroundColor3=Color3.fromRGB(25,70,200);applyFovBtn.Text="Apply FOV";applyFovBtn.TextColor3=Color3.fromRGB(220,230,255);applyFovBtn.TextSize=13;applyFovBtn.Font=Enum.Font.GothamBold;applyFovBtn.BorderSizePixel=0;Instance.new("UICorner",applyFovBtn).CornerRadius=UDim.new(0,8);applyFovBtn.MouseButton1Click:Connect(function()TS:Create(cam,TweenInfo.new(0.4,Enum.EasingStyle.Quint),{FieldOfView=curFOV}):Play();showNotif("FOV → "..tostring(curFOV).."°",Color3.fromRGB(40,120,255));TS:Create(applyFovBtn,TweenInfo.new(0.08),{BackgroundColor3=Color3.fromRGB(60,180,255)}):Play();task.delay(0.15,function()TS:Create(applyFovBtn,TweenInfo.new(0.2),{BackgroundColor3=Color3.fromRGB(25,70,200)}):Play()end)end)
makeSection(pgFov,"ПРЕСЕТЫ",4);local fovPresets={{label="Narrow 60°",fov=60},{label="Normal 70°",fov=70},{label="Wide 90°",fov=90},{label="Ultra 110°",fov=110}};for i,pr in ipairs(fovPresets)do local pb=makeActionBtn(pgFov,pr.label,4+i);pb.MouseButton1Click:Connect(function()setSliderAlpha(fovToAlpha(pr.fov));TS:Create(cam,TweenInfo.new(0.4,Enum.EasingStyle.Quint),{FieldOfView=pr.fov}):Play();showNotif("FOV → "..tostring(pr.fov).."°",Color3.fromRGB(60,140,255))end)end;local bFovReset=makeActionBtn(pgFov,"Reset 70°",9);bFovReset.MouseButton1Click:Connect(function()setSliderAlpha(fovToAlpha(70));TS:Create(cam,TweenInfo.new(0.4,Enum.EasingStyle.Quint),{FieldOfView=70}):Play();showNotif("FOV сброшен → 70°",Color3.fromRGB(100,100,200))end)

-- Settings page (color picker, no GUI recolor)
local pgSettings=makePage("settings");makeSection(pgSettings,"ЦВЕТ ЭФФЕКТОВ",1);local previewRow=Instance.new("Frame",pgSettings);previewRow.Size=UDim2.new(1,0,0,48);previewRow.BackgroundColor3=Color3.fromRGB(15,13,28);previewRow.BorderSizePixel=0;previewRow.LayoutOrder=2;local previewBox=Instance.new("Frame",previewRow);previewBox.Size=UDim2.new(0,36,0,28);previewBox.Position=UDim2.new(0,14,0.5,-14);previewBox.BackgroundColor3=globalColor;previewBox.BorderSizePixel=0;Instance.new("UICorner",previewBox).CornerRadius=UDim.new(0,6);local previewLbl=Instance.new("TextLabel",previewRow);previewLbl.Size=UDim2.new(1,-70,1,0);previewLbl.Position=UDim2.new(0,58,0,0);previewLbl.BackgroundTransparency=1;previewLbl.Text="Текущий цвет эффектов";previewLbl.TextColor3=Color3.fromRGB(170,165,225);previewLbl.TextSize=13;previewLbl.Font=Enum.Font.Gotham;previewLbl.TextXAlignment=Enum.TextXAlignment.Left
local paletteRow=Instance.new("Frame",pgSettings);paletteRow.Size=UDim2.new(1,0,0,155);paletteRow.BackgroundColor3=Color3.fromRGB(15,13,28);paletteRow.BorderSizePixel=0;paletteRow.LayoutOrder=3;local svWidth=250;local svHeight=120;local svFrame=Instance.new("Frame",paletteRow);svFrame.Size=UDim2.new(0,svWidth,0,svHeight);svFrame.Position=UDim2.new(0,14,0,10);svFrame.BackgroundColor3=Color3.fromRGB(255,0,0);svFrame.BorderSizePixel=0;Instance.new("UICorner",svFrame).CornerRadius=UDim.new(0,6);local svWhite=Instance.new("UIGradient",svFrame);svWhite.Color=ColorSequence.new({ColorSequenceKeypoint.new(0,Color3.fromRGB(255,255,255)),ColorSequenceKeypoint.new(1,Color3.fromRGB(255,255,255))});svWhite.Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,0),NumberSequenceKeypoint.new(1,1)});svWhite.Rotation=0;local svDark=Instance.new("Frame",svFrame);svDark.Size=UDim2.new(1,0,1,0);svDark.BackgroundColor3=Color3.fromRGB(0,0,0);svDark.BorderSizePixel=0;svDark.ZIndex=2;Instance.new("UICorner",svDark).CornerRadius=UDim.new(0,6);local svDarkGrad=Instance.new("UIGradient",svDark);svDarkGrad.Color=ColorSequence.new(Color3.fromRGB(0,0,0));svDarkGrad.Transparency=NumberSequence.new({NumberSequenceKeypoint.new(0,1),NumberSequenceKeypoint.new(1,0)});svDarkGrad.Rotation=90;local svCursor=Instance.new("Frame",svFrame);svCursor.Size=UDim2.new(0,14,0,14);svCursor.AnchorPoint=Vector2.new(0.5,0.5);svCursor.Position=UDim2.new(1,-7,0,7);svCursor.BackgroundColor3=Color3.fromRGB(255,255,255);svCursor.BorderSizePixel=0;svCursor.ZIndex=5;Instance.new("UICorner",svCursor).CornerRadius=UDim.new(1,0);local hueSliderFrame=Instance.new("Frame",paletteRow);hueSliderFrame.Size=UDim2.new(0,svWidth,0,14);hueSliderFrame.Position=UDim2.new(0,14,0,svHeight+18);hueSliderFrame.BackgroundColor3=Color3.fromRGB(255,0,0);hueSliderFrame.BorderSizePixel=0;Instance.new("UICorner",hueSliderFrame).CornerRadius=UDim.new(1,0);local hueGrad=Instance.new("UIGradient",hueSliderFrame);hueGrad.Color=ColorSequence.new({ColorSequenceKeypoint.new(0/6,Color3.fromRGB(255,0,0)),ColorSequenceKeypoint.new(1/6,Color3.fromRGB(255,255,0)),ColorSequenceKeypoint.new(2/6,Color3.fromRGB(0,255,0)),ColorSequenceKeypoint.new(3/6,Color3.fromRGB(0,255,255)),ColorSequenceKeypoint.new(4/6,Color3.fromRGB(0,0,255)),ColorSequenceKeypoint.new(5/6,Color3.fromRGB(255,0,255)),ColorSequenceKeypoint.new(6/6,Color3.fromRGB(255,0,0))});local hueCursor=Instance.new("Frame",hueSliderFrame);hueCursor.Size=UDim2.new(0,16,0,20);hueCursor.AnchorPoint=Vector2.new(0.5,0.5);hueCursor.Position=UDim2.new(0,8,0.5,0);hueCursor.BackgroundColor3=Color3.fromRGB(255,255,255);hueCursor.BorderSizePixel=0;hueCursor.ZIndex=5;Instance.new("UICorner",hueCursor).CornerRadius=UDim.new(0,4)
local curH=0.6;local curS=0.7;local curV=1.0
local function rebuild()globalColor=Color3.fromHSV(curH,curS,curV);globalColor2=Color3.fromHSV((curH+0.12)%1,curS,curV*0.7);previewBox.BackgroundColor3=globalColor;svFrame.BackgroundColor3=Color3.fromHSV(curH,1,1);svCursor.Position=UDim2.new(curS,-7,1-curV,7);hueCursor.Position=UDim2.new(curH,-8,0.5,0)end;rebuild()
local dragSV=false;local dragHue=false
svFrame.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dragSV=true;local rx=math.clamp((i.Position.X-svFrame.AbsolutePosition.X)/svFrame.AbsoluteSize.X,0,1);local ry=math.clamp((i.Position.Y-svFrame.AbsolutePosition.Y)/svFrame.AbsoluteSize.Y,0,1);curS=rx;curV=1-ry;rebuild()end end)
hueSliderFrame.InputBegan:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dragHue=true;curH=math.clamp((i.Position.X-hueSliderFrame.AbsolutePosition.X)/hueSliderFrame.AbsoluteSize.X,0,1);rebuild()end end)
UIS.InputEnded:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseButton1 then dragSV=false;dragHue=false end end)
UIS.InputChanged:Connect(function(i)if i.UserInputType==Enum.UserInputType.MouseMovement then if dragSV then local rx=math.clamp((i.Position.X-svFrame.AbsolutePosition.X)/svFrame.AbsoluteSize.X,0,1);local ry=math.clamp((i.Position.Y-svFrame.AbsolutePosition.Y)/svFrame.AbsoluteSize.Y,0,1);curS=rx;curV=1-ry;rebuild()elseif dragHue then curH=math.clamp((i.Position.X-hueSliderFrame.AbsolutePosition.X)/hueSliderFrame.AbsoluteSize.X,0,1);rebuild()end end end)
local applyColorRow=Instance.new("Frame",pgSettings);applyColorRow.Size=UDim2.new(1,0,0,48);applyColorRow.BackgroundColor3=Color3.fromRGB(15,13,28);applyColorRow.BorderSizePixel=0;applyColorRow.LayoutOrder=4;local applyColorBtn=Instance.new("TextButton",applyColorRow);applyColorBtn.Size=UDim2.new(1,-28,0,30);applyColorBtn.Position=UDim2.new(0,14,0.5,-15);applyColorBtn.BackgroundColor3=Color3.fromRGB(30,80,200);applyColorBtn.Text="Применить цвет ко всем эффектам";applyColorBtn.TextColor3=Color3.fromRGB(220,230,255);applyColorBtn.TextSize=13;applyColorBtn.Font=Enum.Font.GothamBold;applyColorBtn.BorderSizePixel=0;Instance.new("UICorner",applyColorBtn).CornerRadius=UDim.new(0,8);applyColorBtn.MouseButton1Click:Connect(function()applyGlobalColor();TS:Create(applyColorBtn,TweenInfo.new(0.08),{BackgroundColor3=Color3.fromRGB(60,200,255)}):Play();task.delay(0.2,function()TS:Create(applyColorBtn,TweenInfo.new(0.2),{BackgroundColor3=Color3.fromRGB(30,80,200)}):Play()end)end)
makeSection(pgSettings,"БЫСТРЫЙ ВЫБОР",5);local quickColors={{name="Синий",h=0.60,s=0.8,v=1.0},{name="Фиолетовый",h=0.75,s=0.8,v=1.0},{name="Красный",h=0.0,s=0.9,v=1.0},{name="Зеленый",h=0.35,s=0.8,v=1.0},{name="Cyan",h=0.50,s=0.9,v=1.0},{name="Золотой",h=0.13,s=0.9,v=1.0},{name="Розовый",h=0.87,s=0.7,v=1.0},{name="Белый",h=0.0,s=0.0,v=1.0}};for i,qc in ipairs(quickColors)do local qb=makeActionBtn(pgSettings,qc.name,5+i);qb.MouseButton1Click:Connect(function()curH=qc.h;curS=qc.s;curV=qc.v;rebuild();applyGlobalColor()end)end

-- Navigation
local navItems={{label="  Sky",page="sky"},{label="  Weather",page="weather"},{label="  Visual",page="visual"},{label="  FOV",page="fov"},{label="  Settings",page="settings"},{label="  Misc",page="misc"}};local navBtns={};local curPage=nil
local function selectPage(name)for n,pg in pairs(pages)do pg.Visible=(n==name)end;for _,nb in ipairs(navBtns)do local act=nb.pageName==name;TS:Create(nb.btn,TweenInfo.new(0.12),{BackgroundColor3=act and Color3.fromRGB(42,38,102)or Color3.fromRGB(12,10,22)}):Play();nb.dot.Visible=act end;curPage=name end
for i,item in ipairs(navItems)do local btn=Instance.new("TextButton",navPanel);btn.Size=UDim2.new(1,0,0,40);btn.LayoutOrder=i;btn.BackgroundColor3=Color3.fromRGB(12,10,22);btn.Text="";btn.BorderSizePixel=0;local dot=Instance.new("Frame",btn);dot.Size=UDim2.new(0,3,0.5,0);dot.Position=UDim2.new(0,0,0.25,0);dot.BackgroundColor3=Color3.fromRGB(95,85,205);dot.BorderSizePixel=0;dot.Visible=false;local lbl=Instance.new("TextLabel",btn);lbl.Size=UDim2.new(1,-8,1,0);lbl.Position=UDim2.new(0,12,0,0);lbl.BackgroundTransparency=1;lbl.Text=item.label;lbl.TextColor3=Color3.fromRGB(160,155,215);lbl.TextSize=13;lbl.Font=Enum.Font.Gotham;lbl.TextXAlignment=Enum.TextXAlignment.Left;btn.MouseButton1Click:Connect(function()selectPage(item.page)end);btn.MouseEnter:Connect(function()if curPage~=item.page then TS:Create(btn,TweenInfo.new(0.1),{BackgroundColor3=Color3.fromRGB(20,18,42)}):Play()end end);btn.MouseLeave:Connect(function()if curPage~=item.page then TS:Create(btn,TweenInfo.new(0.1),{BackgroundColor3=Color3.fromRGB(12,10,22)}):Play()end end);table.insert(navBtns,{btn=btn,dot=dot,pageName=item.page})end
selectPage("sky")

closeBtn.MouseButton1Click:Connect(function()main.Visible=false;UIS.MouseBehavior=Enum.MouseBehavior.LockCenter;UIS.MouseIconEnabled=false;showNotif("Kitty скрыт",Color3.fromRGB(75,65,155))end)
local minimized=false;minBtn.MouseButton1Click:Connect(function()minimized=not minimized;navPanel.Visible=not minimized;contentArea.Visible=not minimized;divLine.Visible=not minimized;main.Size=minimized and UDim2.new(0,545,0,44)or UDim2.new(0,545,0,400)end)
local guiOpen=true;UIS.InputBegan:Connect(function(inp)if inp.KeyCode==Enum.KeyCode.RightControl then guiOpen=not guiOpen;main.Visible=guiOpen;if guiOpen then UIS.MouseBehavior=Enum.MouseBehavior.Default;UIS.MouseIconEnabled=true;showNotif("Kitty открыт",Color3.fromRGB(90,80,200))else UIS.MouseBehavior=Enum.MouseBehavior.LockCenter;UIS.MouseIconEnabled=false;showNotif("Kitty скрыт",Color3.fromRGB(60,55,130))end end end)
task.wait(0.8);showNotif("Kitty Script v3.2 запущен!",Color3.fromRGB(100,85,220));task.wait(1.2);showNotif("Привет, "..pl.Name.."!",Color3.fromRGB(60,160,100));print("[Kitty v3.2] Готово! RightCtrl — открыть/скрыть.")
